services:
  validator:
    image: val_img_1
    build:
      context: .
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src
    entrypoint: ["python", "-m", "ftd_omop_validator.omop_file_validator"]
